version: '3.7'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=astorun-dev
      - POSTGRES_PASSWORD=astorun-dev
      - POSTGRES_DB=astorun-dev
    ports:
      - 5432:5432
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000          
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/astorun_2022
    depends_on:
      - db
    env_file:
      - ./.env.dev      
  
 
volumes:
  postgres_data:            
   

