version: '3.7'

services:
  web:
    build: .
    command: gunicorn FrontendPractice.wsgi:application --bind 0.0.0.0:8000
    expose: 
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/home/app/astorun_2022/static
      - media_volume:/home/app/astorun_2022/media  
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  nginx:
    build : ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/astorun_2022/static
      - media_volume:/home/app/astorun_2022/media
    depends_on:
      - web    

volumes:
  postgres_data:
  static_volume: 
  media_volume: 