version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000  
    ports:
      - "8000:8000"
    volumes:
      - .:/astorun_2022
    depends_on:
      - db    
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    #   - POSTGRES_DB=postgres
    environment:  
      - "POSTGRES_HOST_AUTH_METHOD=trust"
#     ports:
#       - 5432:5432

volumes:
  postgres_data:            
   

