# Generated by Django 3.2.9 on 2022-11-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='collection_img/', verbose_name='Изображение коллекции')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
        ),
    ]
