# Generated by Django 3.2.9 on 2022-07-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_actvie',
            field=models.BooleanField(default=True),
        ),
    ]
