# Generated by Django 3.2.9 on 2022-07-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collection_is_actvie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='is_actvie',
            new_name='actvie',
        ),
    ]
