# Generated by Django 3.2.9 on 2022-07-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_rename_is_actvie_collection_actvie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='actvie',
            new_name='is_active',
        ),
    ]
