# Generated by Django 3.2.9 on 2022-07-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='is_active',
        ),
    ]
